import React from "react";
import Head from "next/head";
import Main from "src/components/main";

const Home = () => {
  return (
    <div>
      <Head>
        <title>clipboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>clipboard</header>
      <Main />
    </div>
  );
};

export default Home;
